name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Run flake8
        run: flake8 . --exclude=venv,env,.venv,.git,__pycache__,.ipynb_checkpoints

      - name: Run tests (optional)
        run: echo "✅ No tests configured yet"
